# Generated by Django 5.2.1 on 2025-05-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_profile_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='friends',
            new_name='following',
        ),
    ]
