# Generated by Django 5.2.1 on 2025-05-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_rename_friends_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
